### ISSUE TITLE
系统找不到指定的驱动器

### ISSUE THREAD

**Issue by devinli123** [oniisancr/COC_robot#2]
![image](https://github.com/oniisancr/COC_robot/assets/43318470/c4185114-4e2d-459d-b571-6c3bd9e9a333)
这个是什么情况呀

**Comment by oniisancr** [comment]
可能是库的问题。重新安装下从cv库试试。
`pip install opencv-python==4.8.1.78`
使用dev分支代码。

**Comment by oniisancr** [comment]
可能是颜色空间错误，可尝试修改为
 ` screenshot_cv = cv2.imdecode(screenshot_np, cv2.IMREAD_COLOR)`
建议使用dev分支代码。
@devinli123

**Comment by oniisancr** [comment]
1. 查看`adb devices`，是否存在可调试的设备。
2. 确保已打开手机调试。
- 新的代码已提交到dev分支。
@devinli123
