### ISSUE TITLE
手机系统问题

### ISSUE THREAD

**Issue by xiaotantanya** [oniisancr/COC_robot#5]
我手机系统是安卓13，有没有测试过能不能运行？

**Comment by oniisancr** [comment]
由于手机分辨率不同，脚本无法正常匹配到相应元素。大概率会无法正常运行脚本，出现点击错误等情况。
可以尝试:
- 手动截取并替换images路径下各个元素，这样应该就可以正常运行了.
- 或者更改手机分辨率。
